/**
 * Génère src/data/mobilityStretchCatalog.js (72 entrées mobilité).
 * node scripts/generateMobilityCatalog.mjs
 */
import fs from 'fs';
import path from 'path';

const OUT = path.join(process.cwd(), 'src/data/mobilityStretchCatalog.js');

/** @type {Array<object>} */
const ITEMS = [
  // ── GENOUX (20) ──
  { key: 'mob_genou_squat_profond_assiste', name: 'Squat profond assisté', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 1, dur: 60, eq: 'Support (barre, porte)', pos: 'Debout', pri: ['Quadriceps', 'Fessiers'], sec: ['Mollets', 'Core'], desc: 'Améliore l’amplitude genou-cheville en squat sans surcharge vertébrale.', inst: 'Tiens un support devant toi, pieds largeur épaules. Descends en squat le plus bas possible en gardant les talons au sol et le buste relâché. Maintiens 30–45 s ou fais 8 oscillations lentes. Remonte en poussant sur les jambes, pas en tirant sur les bras.', ci: ['Douleur fémoro-patellaire aiguë'], var: ['assisted deep squat', 'squat profond'] },
  { key: 'mob_genou_knee_over_toes_lunge', name: 'Knee Over Toes — fente avant', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 50, eq: 'Aucun', pos: 'Fente avant', pri: ['Quadriceps', 'Soléaire'], sec: ['Fessiers', 'Mollets'], desc: 'Travaille la tolérance du genou en flexion profonde et la dorsiflexion de cheville.', inst: 'Fente avant, genou bien au-delà des orteils sans lever le talon arrière. Buste droit, bassin neutre. Pousse doucement le genou avant sur 3 s, relâche 2 s, répète 8–10 fois puis maintien 20 s. Change de jambe.', ci: ['Tendinopathie rotulienne aiguë'], var: ['knee over toes', 'KOT lunge'] },
  { key: 'mob_genou_atg_split_squat', name: 'ATG split squat', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 3, dur: 55, eq: 'Aucun', pos: 'Fente profonde', pri: ['Quadriceps', 'Fessiers'], sec: ['Mollets', 'Fléchisseurs de hanche'], desc: 'Fente « ass to grass » pour étirer le quadriceps et gagner en amplitude de flexion du genou.', inst: 'Grande fente, genou avant au maximum sans douleur, talon arrière relevé ou au sol selon confort. Bassin bas, buste vertical. Maintiens 25–40 s ou 6 reps lentes avec pause en bas. Jambe opposée.', ci: ['Instabilité ligamentaire genou'], var: ['ATG split squat', 'fente profonde'] },
  { key: 'mob_genou_heel_sit', name: 'Heel sit — assis sur les talons', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 45, eq: 'Tapis', pos: 'À genoux', pri: ['Quadriceps', 'Genou'], sec: ['Mollets', 'Fascia plantaire'], desc: 'Restaure la flexion complète du genou et assouplit l’avant de la cuisse.', inst: 'À genoux, fesses sur les talons, orteils pointés ou relâchés selon confort cheville. Dos droit, respiration nasale. Commence 20–30 s, progresse vers 60 s. Si douleur rotulienne, coussin sous les tibias.', ci: ['Genou en flexion maximale douloureux'], var: ['heel sit', 'assise talons'] },
  { key: 'mob_genou_quad_stretch_sol', name: 'Étirement quadriceps au sol', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 1, dur: 50, eq: 'Aucun', pos: 'Côté ou ventre', pri: ['Quadriceps'], sec: ['Fléchisseurs de hanche', 'Genou'], desc: 'Assouplit l’avant de la cuisse pour diminuer la tension sur la rotule en flexion.', inst: 'Sur le côté, attrape la cheville et tire le talon vers les fesses sans cambrer les lombaires. Genou pointé vers le bas, bassin légèrement basculé postérieur. 25 s × 2 par jambe.', ci: ['Entorse genou récente'], var: ['quad stretch side lying'] },
  { key: 'mob_genou_couch_stretch', name: 'Couch stretch', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 90, eq: 'Mur ou canapé', pos: 'Fente genou au mur', pri: ['Quadriceps', 'Fléchisseurs de hanche'], sec: ['Psoas', 'Genou'], desc: 'Étirement intense du quadriceps et du psoas — clé pour la posture et les squats profonds.', inst: 'Genou arrière au sol contre un mur, pied pointé vers le haut. Jambe avant en appui, buste droit. Serre les fessiers pour éviter la cambrure lombaire. 45–90 s par jambe, respiration calme.', ci: ['Douleur rotulienne', 'hernie discale non contrôlée'], var: ['couch stretch', 'étirement canapé'] },
  { key: 'mob_genou_tke_elastique', name: 'Terminal Knee Extensions (TKE)', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 1, dur: 45, eq: 'Élastique', pos: 'Debout', pri: ['Quadriceps', 'Vaste médial'], sec: ['Genou'], desc: 'Renforce le quadriceps en fin d’extension sans charge axiale lourde.', inst: 'Élastique autour d’un poteau, autre extrémité derrière le genou. Jambe d’appui légèrement fléchie. Étends le genou contre la résistance en contractant le quadriceps 2 s en haut. 12–15 reps lentes. Utile en rééducation et échauffement.', ci: ['Douleur en extension forcée'], var: ['TKE', 'terminal knee extension'] },
  { key: 'mob_genou_spanish_squat', name: 'Spanish squat', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 50, eq: 'Sangle ou élastique', pos: 'Squat isométrique', pri: ['Quadriceps', 'Tendon rotulien'], sec: ['Fessiers', 'Core'], desc: 'Charge le tendon rotulien en angle favorable — outil courant en prévention tendinopathie.', inst: 'Sangle fixe derrière les genoux, recule pour tension. Squat vertical, genoux avancés, buste droit. Maintiens 30–45 s ou 8–12 reps lentes. Ne laisse pas les genoux rentrer.', ci: ['Tendinopathie rotulienne aiguë non diagnostiquée'], var: ['spanish squat'] },
  { key: 'mob_genou_reverse_nordic', name: 'Reverse Nordic curl', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 3, dur: 40, eq: 'Tapis', pos: 'À genoux', pri: ['Quadriceps'], sec: ['Fléchisseurs de hanche', 'Core'], desc: 'Renforcement excentrique du quadriceps en amplitude complète de genou.', inst: 'À genoux, corps droit des genoux à la tête. Penche-toi lentement vers l’arrière en gardant les hanches étendues. Amplitude où tu contrôles, remonte en contractant les quadriceps. 5–8 reps. Progresse la profondeur sur plusieurs semaines.', ci: ['Douleur rotulienne', 'genou instable'], var: ['reverse nordic'] },
  { key: 'mob_genou_tibialis_raises', name: 'Tibialis raises', cat: 'Mobilité genoux', zone: 'mollets', diff: 1, dur: 40, eq: 'Mur', pos: 'Dos au mur', pri: ['Tibial antérieur'], sec: ['Mollets', 'Cheville'], desc: 'Renforce le tibial antérieur — souvent négligé, utile pour la course et la stabilité du genou.', inst: 'Dos au mur, pieds ~20 cm du mur. Glisse les fesses le long du mur en levant les pointes de pieds (dorsiflexion). Redescends contrôlé. 15–20 reps. Peut se faire assis jambes pendantes.', ci: ['Syndrome de loge antérieur'], var: ['tib raises', 'tibialis anterior'] },
  { key: 'mob_genou_ischio_dynamique', name: 'Étirement dynamique des ischios', cat: 'Mobilité genoux', zone: 'ischios', diff: 1, dur: 45, eq: 'Aucun', pos: 'Debout', pri: ['Ischio-jambiers'], sec: ['Fessiers', 'Lombaires'], desc: 'Mobilise l’arrière de cuisse pour réduire la tension sur le genou en extension.', inst: 'Debout, appui sur une jambe. Balaye l’autre jambe devant toi genou quasi tendu, amplitude modérée sans arrondir le dos. 10–12 balayages par jambe. Idéal en échauffement avant course ou musculation jambes.', ci: ['Lombalgie aiguë'], var: ['leg swings hamstring', 'balancier ischios'] },
  { key: 'mob_genou_leg_swings_sagittal', name: 'Leg swings avant / arrière', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 1, dur: 40, eq: 'Support léger', pos: 'Debout', pri: ['Fléchisseurs de hanche', 'Ischio-jambiers'], sec: ['Quadriceps', 'Mollets'], desc: 'Prépare genou et hanche en mouvement oscillatoire contrôlé.', inst: 'Appui sur un mur, buste stable. Balance la jambe libre avant-arrière sans forcer l’amplitude. 15–20 oscillations fluides par jambe. Augmente l’amplitude progressivement sur la séance.', ci: ['Instabilité hanche'], var: ['leg swings', 'balanciers sagittaux'] },
  { key: 'mob_genou_cossack_squat', name: 'Cossack squat', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 3, dur: 55, eq: 'Aucun', pos: 'Squat latéral', pri: ['Adducteurs', 'Quadriceps'], sec: ['Mollets', 'Fessiers'], desc: 'Mobilité latérale genou-hanche-cheville en charge partielle du corps.', inst: 'Pieds très écartés, un genou fléchi sur le côté, l’autre jambe tendue pied à plat ou talon levé selon mobilité. Buste droit, fesses en arrière. 6–8 reps lentes par côté ou maintien 20 s. Descends seulement dans l’amplitude contrôlée.', ci: ['Entorse genou', 'adducteurs déchirés'], var: ['cossack squat', 'squat latéral'] },
  { key: 'mob_genou_step_down_controle', name: 'Step-down contrôlé', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 50, eq: 'Marche ou box basse', pos: 'Debout sur marche', pri: ['Quadriceps', 'Fessiers'], sec: ['Mollets', 'Core'], desc: 'Apprentissage du contrôle excentrique du genou en descente — prévention douleur rotulienne.', inst: 'Sur une marche basse, jambe de travail sur la marche. Descends lentement l’autre pied au sol en contrôlant le genou (ne rentre pas vers l’intérieur). Remonte. 8–10 reps par jambe. Mains sur hanches pour le feedback.', ci: ['Douleur rotulienne en charge'], var: ['step down', 'descente marche'] },
  { key: 'mob_genou_wall_sit', name: 'Wall sit', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 60, eq: 'Mur', pos: 'Assis contre mur', pri: ['Quadriceps'], sec: ['Fessiers', 'Core'], desc: 'Endurance isométrique des quadriceps pour stabilité du genou.', inst: 'Dos au mur, descend en squat jusqu’à ~90° genou si possible. Cuisses parallèles au sol, genoux alignés avec les orteils. Maintiens 30–60 s. Respire normalement. Progresse durée avant d’ajouter charge.', ci: ['Hypertension non contrôlée (prudence isométrique)'], var: ['wall sit', 'chaise murale'] },
  { key: 'mob_genou_banded_knee_distraction', name: 'Banded knee distraction', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 2, dur: 45, eq: 'Élastique', pos: 'Fente ou assis', pri: ['Genou', 'Quadriceps'], sec: ['Mollets'], desc: 'Mobilisation articulaire douce du genou avec traction pour gagner quelques degrés de flexion.', inst: 'Élastique autour de la cuisse, ancrage bas. Fente avant, laisse l’élastique tirer légèrement le fémur sur le tibia tout en oscillant le genou dans une petite amplitude confortable. 10–15 oscillations. Pas de douleur vive.', ci: ['Arthrite aiguë', 'ménisque irrité'], var: ['knee distraction', 'mob genou élastique'] },
  { key: 'mob_genou_ankle_dorsiflexion_genou', name: 'Dorsiflexion cheville pour le genou', cat: 'Mobilité genoux', zone: 'mollets', diff: 1, dur: 45, eq: 'Mur', pos: 'Fente talon au sol', pri: ['Soléaire', 'Gastrocnémiens'], sec: ['Genou', 'Fascia crural'], desc: 'La cheville limite souvent le squat : ce drill libère la chaîne inférieure du genou.', inst: 'Pied arrière à plat, fente vers le mur sans lever le talon. 10 pulses puis maintien 15 s. Mesure la distance pied-mur pour suivre les progrès. Change de jambe.', ci: ['Entorse cheville'], var: ['ankle dorsiflexion', 'genou mur'] },
  { key: 'mob_genou_nordic_assiste', name: 'Nordic curl assisté', cat: 'Mobilité genoux', zone: 'ischios', diff: 2, dur: 45, eq: 'Partenaire ou fixation', pos: 'À genoux', pri: ['Ischio-jambiers'], sec: ['Fessiers', 'Genou'], desc: 'Renforcement ischios en excentrique — protecteur du genou en sport à changements de direction.', inst: 'Chevilles bloquées, corps droit. Descends lentement vers l’avant en freinant avec les ischios, pousse sur les mains au besoin pour limiter la charge. 5–8 reps. Progresse vers moins d’assistance.', ci: ['Claquage ischios'], var: ['assisted nordic curl'] },
  { key: 'mob_genou_marche_arriere', name: 'Marche arrière', cat: 'Mobilité genoux', zone: 'quadriceps', diff: 1, dur: 60, eq: 'Aucun', pos: 'Marche', pri: ['Quadriceps', 'Fessiers'], sec: ['Mollets', 'Core'], desc: 'Renforcement doux et mobilité en chaîne fermée, souvent mieux toléré que la fente avant au début.', inst: 'Marche arrière sur 10–20 m en poussant avec l’avant du pied, petits pas, buste droit. Peut se faire en pente légère pour plus d’intensité. 2–4 allers-retours. Utile rééducation genou et échauffement.', ci: ['Terrain glissant'], var: ['backward walk', 'marche arrière genou'] },

  // ── HANCHES (17 nouveaux, Cossack/Deep squat existent) ──
  { key: 'mob_hanche_90_90_stretch', name: '90/90 stretch', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 70, eq: 'Tapis', pos: 'Assis 90/90', pri: ['Rotateurs externes de hanche', 'Fessiers'], sec: ['Adducteurs', 'Ischio-jambiers'], desc: 'Rotation interne et externe de hanche — base de la mobilité du bassin.', inst: 'Assis, une jambe devant 90°, l’autre sur le côté 90°. Penche le buste vers la jambe avant pour RE, vers la jambe arrière pour RI. 30–45 s chaque orientation, change de côté.', ci: ['Douleur hanche FAI'], var: ['90/90', 'ninety ninety'] },
  { key: 'mob_hanche_hip_cars', name: 'Hip CARs', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 60, eq: 'Support', pos: 'Debout appui', pri: ['Fessiers', 'Fléchisseurs de hanche'], sec: ['Core', 'Adducteurs'], desc: 'Rotations articulaires contrôlées — entretien de l’amplitude sans étirement passif agressif.', inst: 'Appui sur un mur, lève le genou, ouvre en rotation externe, étends, reviens en cercle lent sans bouger le tronc. 5 cercles par jambe. Amplitude maximale SANS compensation lombaire.', ci: ['Hanche douloureuse en fin d’amplitude'], var: ['hip CARs', 'controlled articular rotations'] },
  { key: 'mob_hanche_pigeon_stretch', name: 'Pigeon stretch', cat: 'Mobilité hanches', zone: 'fessiers', diff: 2, dur: 90, eq: 'Tapis', pos: 'Sol — pigeon', pri: ['Fessiers', 'Piriforme'], sec: ['Ischio-jambiers', 'Lombaires'], desc: 'Ouverture de la hanche postérieure et des rotateurs — soulage tensions bassin-dos.', inst: 'Jambe avant pliée devant, arrière tendue. Descends le buste selon confort, fesses du côté avant légèrement tirées. 45–90 s par côté. Variante sur table si genou sensible.', ci: ['Douleur genou en flexion'], var: ['pigeon', 'figure 4 au sol'] },
  { key: 'mob_hanche_frog_stretch', name: 'Frog stretch', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 70, eq: 'Tapis', pos: 'À quatre pattes jambes écartées', pri: ['Adducteurs'], sec: ['Fessiers', 'Lombaires'], desc: 'Ouverture des adducteurs et mobilité interne de hanche.', inst: 'À genoux, genoux très écartés, pieds vers l’extérieur. Pousse les fesses vers les talons ou avant selon variante, dos neutre. 30–60 s. Respire dans l’étirement sans rebond.', ci: ['Douleur aiguë adducteurs'], var: ['frog stretch', 'grenouille'] },
  { key: 'mob_hanche_leg_swings_lateral', name: 'Leg swings latéraux', cat: 'Mobilité hanches', zone: 'hanches', diff: 1, dur: 40, eq: 'Support', pos: 'Debout', pri: ['Adducteurs', 'Fessiers moyen'], sec: ['Core', 'Quadriceps'], desc: 'Prépare hanche et bassin en plan frontal avant course ou squat.', inst: 'Appui mur, jambe libre qui balaie sur le côté croisant la ligne médiane sans tourner le tronc. 15–20 reps par jambe. Amplitude progressive.', ci: ['Instabilité bassin'], var: ['lateral leg swings'] },
  { key: 'mob_hanche_worlds_greatest', name: "World's Greatest Stretch", cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 60, eq: 'Aucun', pos: 'Fente profonde rotation', pri: ['Fléchisseurs de hanche', 'Thoracique'], sec: ['Ischio-jambiers', 'Mollets'], desc: 'Mobilité globale hanche-rachis — classique des échauffements athlétiques.', inst: 'Grande fente, main opposée au sol, coude vers l’intérieur du pied avant, ouvre l’autre bras au plafond en suivant du regard. Reviens, change de côté. 5–6 reps lentes par côté.', ci: ['Lombalgie aiguë'], var: ['worlds greatest stretch', 'WGS'] },
  { key: 'mob_hanche_lizard_stretch', name: 'Lizard stretch', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 60, eq: 'Tapis', pos: 'Fente basse mains sol', pri: ['Fléchisseurs de hanche', 'Psoas'], sec: ['Adducteurs', 'Quadriceps'], desc: 'Étirement profond des fléchisseurs — utile après longue position assise.', inst: 'Fente basse, mains à l’intérieur du pied avant. Avance le bassin, dos plat ou légère cambrure thoracique seulement. 30–45 s par jambe.', ci: ['Hernie discale'], var: ['lizard pose', 'lézard'] },
  { key: 'mob_hanche_fire_hydrants', name: 'Fire hydrants', cat: 'Mobilité hanches', zone: 'fessiers', diff: 1, dur: 45, eq: 'Tapis', pos: 'Quatre pattes', pri: ['Fessiers moyen', 'Rotateurs de hanche'], sec: ['Core', 'Quadriceps'], desc: 'Activation et mobilité de hanche en abduction — stabilité du bassin.', inst: 'Quatre pattes, genou fléchi à 90°, lève la jambe sur le côté sans basculer le bassin. 12–15 reps lentes par côté. Peut ajouter élastique cheville.', ci: ['Douleur poignet en appui'], var: ['fire hydrant', 'chien arrosage'] },
  { key: 'mob_hanche_clamshells', name: 'Clamshells', cat: 'Mobilité hanches', zone: 'fessiers', diff: 1, dur: 45, eq: 'Élastique (optionnel)', pos: 'Côté', pri: ['Fessiers moyen'], sec: ['Rotateurs externes', 'Core'], desc: 'Active les rotateurs externes — souvent déficitaires quand les genoux rentrent.', inst: 'Sur le côté, genoux fléchis, pieds collés. Ouvre le genou supérieur sans rouler le bassin. 15–20 reps. Élastique au-dessus des genoux pour plus de résistance.', ci: ['Douleur hanche latérale'], var: ['clamshell', 'palourde'] },
  { key: 'mob_hanche_standing_circles', name: 'Standing hip circles', cat: 'Mobilité hanches', zone: 'hanches', diff: 1, dur: 40, eq: 'Support', pos: 'Debout', pri: ['Fessiers', 'Fléchisseurs de hanche'], sec: ['Core', 'Mollets'], desc: 'Mobilité dynamique de hanche debout — échauffement rapide.', inst: 'Appui léger, jambe libre : grands cercles lents hanche (10 sens horaire, 10 anti-horaire). Tronc stable. Change de jambe.', ci: ['Perte d’équilibre'], var: ['hip circles standing'] },
  { key: 'mob_hanche_jefferson_curl_leger', name: 'Jefferson curl léger', cat: 'Mobilité hanches', zone: 'ischios', diff: 3, dur: 50, eq: 'Haltère léger ou bâton', pos: 'Debout', pri: ['Ischio-jambiers', 'Érecteurs du rachis'], sec: ['Fessiers', 'Mollets'], desc: 'Mobilité chaîne postérieure et bassin en flexion segmentée contrôlée.', inst: 'Debout, charge très légère. Arrondis vertèbre par vertèbre vers le bas, genoux légèrement fléchis. Descends jusqu’à tension modérée ischios, remonte lentement. 6–8 reps. Pas de charge lourde sans encadrement.', ci: ['Hernie discale', 'lombalgie aiguë'], var: ['jefferson curl'] },
  { key: 'mob_hanche_adductor_rock_back', name: 'Adductor rock back', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 50, eq: 'Tapis', pos: 'Quatre pattes genou écarté', pri: ['Adducteurs'], sec: ['Fessiers', 'Core'], desc: 'Mobilité des adducteurs en charge partielle — complément du frog stretch.', inst: 'Quatre pattes, un genou écarté sur le côté, pied à plat. Bascule le bassin vers le talon en gardant le dos neutre. 10–12 rocks par côté.', ci: ['Douleur adducteurs'], var: ['adductor rockback'] },
  { key: 'mob_hanche_slrdl_leger', name: 'Single-leg RDL léger', cat: 'Mobilité hanches', zone: 'ischios', diff: 2, dur: 45, eq: 'Haltère léger', pos: 'Un pied', pri: ['Ischio-jambiers', 'Fessiers'], sec: ['Core', 'Mollets'], desc: 'Stabilité hanche et ischios en unilatéral — contrôle du bassin.', inst: 'Un pied au sol, autre jambe en arrière. Penche le buste, jambe libre prolonge le corps. Charge légère ou sans charge. 8 reps par jambe. Bassin parallèle au sol.', ci: ['Vertige', 'lombalgie'], var: ['single leg rdl'] },
  { key: 'mob_hanche_seated_ir_drill', name: 'Seated internal rotation drill', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 45, eq: 'Chaise', pos: 'Assis bord', pri: ['Rotateurs internes de hanche'], sec: ['Adducteurs', 'Fessiers'], desc: 'Travail spécifique de rotation interne souvent limitée chez les sportifs.', inst: 'Assis bord chaise, genou fléchi, pied fixe. Laisse le genou tomber vers l’intérieur sous gravité ou pousse doucement avec la main. 20–30 s × 2 par hanche.', ci: ['Douleur aiguë hanche'], var: ['seated IR hip'] },
  { key: 'mob_hanche_kneeling_hip_opener', name: 'Kneeling hip opener', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 55, eq: 'Tapis', pos: 'Fente genou au sol', pri: ['Fléchisseurs de hanche', 'Psoas'], sec: ['Quadriceps', 'Fessiers'], desc: 'Ouverture progressive des fléchisseurs en position stable.', inst: 'Fente basse, genou arrière au sol. Avance le bassin en gardant le buste vertical, serre la fesse arrière. 30–45 s par côté. Peut ajouter léger side bend ipsilatéral.', ci: ['Douleur rotulienne'], var: ['kneeling hip opener'] },
  { key: 'mob_hanche_bear_sit_transitions', name: 'Bear sit transitions', cat: 'Mobilité hanches', zone: 'hanches', diff: 2, dur: 50, eq: 'Tapis', pos: 'Assis sol jambes croisées', pri: ['Rotateurs de hanche', 'Adducteurs'], sec: ['Core', 'Fessiers'], desc: 'Transitions au sol pour fluidifier rotations de hanche (90/90 actif).', inst: 'Assis en 90/90, lève les genoux, bascule les jambes d’un côté à l’autre sans t’effondrer. 8–12 transitions lentes. Mains au sol derrière si besoin.', ci: ['Douleur genou'], var: ['bear sit', '90/90 switches'] },

  // ── BASSIN / antéversion (12 nouveaux) ──
  { key: 'mob_bassin_posterior_pelvic_tilt', name: 'Posterior pelvic tilt', cat: 'Mobilité bassin', zone: 'lombaires', diff: 1, dur: 45, eq: 'Tapis', pos: 'Allongé dos', pri: ['Abdominaux', 'Fessiers'], sec: ['Fléchisseurs de hanche', 'Lombaires'], desc: 'Apprend à rétroverser le bassin — contre l’antéversion et la cambrure excessive.', inst: 'Allongé, genoux fléchis. Aplatis le bas du dos contre le sol en contractant abdos et fessiers. Maintiens 5 s, relâche. 12–15 reps. Ressenti : os du sacrum qui « roule » vers le haut.', ci: ['Grossesse avancée (avis médical)'], var: ['PPT', 'rétroversion bassin'] },
  { key: 'mob_bassin_dead_bug', name: 'Dead bug', cat: 'Mobilité bassin', zone: 'lombaires', diff: 2, dur: 50, eq: 'Tapis', pos: 'Allongé', pri: ['Abdominaux', 'Transverse'], sec: ['Fléchisseurs de hanche', 'Quadriceps'], desc: 'Gainage avec contrôle lombaire — pilier anti-antéversion.', inst: 'Allongé, bras au plafond, genoux 90°. Descends jambe opposée au bras sans décoller les lombaires du sol. Alterne lentement. 8–10 reps par côté.', ci: ['Lombalgie aiguë'], var: ['dead bug'] },
  { key: 'mob_bassin_plank', name: 'Plank', cat: 'Mobilité bassin', zone: 'tronc', diff: 2, dur: 45, eq: 'Tapis', pos: 'Planche', pri: ['Abdominaux', 'Transverse'], sec: ['Épaules', 'Fessiers'], desc: 'Gainage global qui empêche la cambrure lombaire sous charge.', inst: 'Avant-bras et pieds au sol, corps aligné. Serre fessiers et abdos, ne laisse pas les hanches s’affaisser. 20–45 s. Respiration continue.', ci: ['Douleur poignet'], var: ['plank', 'planche'] },
  { key: 'mob_bassin_side_plank', name: 'Side plank', cat: 'Mobilité bassin', zone: 'tronc', diff: 2, dur: 40, eq: 'Tapis', pos: 'Planche latérale', pri: ['Obliques', 'Fessiers moyen'], sec: ['Épaules', 'Core'], desc: 'Stabilité latérale du tronc — équilibre des forces autour du bassin.', inst: 'Appui avant-bras et côté du pied, hanches hautes, corps aligné. 20–35 s par côté. Genou au sol pour version facile.', ci: ['Épaule douloureuse'], var: ['side plank'] },
  { key: 'mob_bassin_hollow_hold', name: 'Hollow body hold', cat: 'Mobilité bassin', zone: 'tronc', diff: 3, dur: 35, eq: 'Tapis', pos: 'Allongé', pri: ['Abdominaux', 'Transverse'], sec: ['Fléchisseurs de hanche', 'Quadriceps'], desc: 'Contrôle abdominal profond en position globale.', inst: 'Allongé, presse le bas du dos au sol, lève épaules et jambes tendues basses. Bras le long du corps ou au-dessus de la tête. 15–30 s. Réduis l’amplitude si les lombaires se décollent.', ci: ['Hernie discale'], var: ['hollow hold'] },
  { key: 'mob_bassin_bird_dog', name: 'Bird dog', cat: 'Mobilité bassin', zone: 'lombaires', diff: 1, dur: 45, eq: 'Tapis', pos: 'Quatre pattes', pri: ['Érecteurs du rachis', 'Fessiers'], sec: ['Abdominaux', 'Épaules'], desc: 'Stabilité lombaire et coordination tronc-bassin.', inst: 'Quatre pattes, étends bras et jambe opposés sans rotation du bassin. Maintiens 3 s, alterne. 8–10 par côté. Regard au sol pour garder le cou neutre.', ci: ['Douleur poignet'], var: ['bird dog', 'chien oiseau'] },
  { key: 'mob_bassin_hamstring_stretch', name: 'Hamstring stretch — bassin neutre', cat: 'Mobilité bassin', zone: 'ischios', diff: 1, dur: 55, eq: 'Sangle', pos: 'Allongé ou assis', pri: ['Ischio-jambiers'], sec: ['Fessiers', 'Lombaires'], desc: 'Rééquilibre la chaîne postérieure sans cambrer pour « aller plus loin ».', inst: 'Allongé, jambe vers le plafond avec sangle. Garde le sacrum au sol, flexion depuis la hanche seulement. 30–45 s par jambe.', ci: ['Sciatalgie aiguë'], var: ['hamstring stretch'] },
  { key: 'mob_bassin_reverse_crunch', name: 'Reverse crunch', cat: 'Mobilité bassin', zone: 'tronc', diff: 2, dur: 40, eq: 'Tapis', pos: 'Allongé', pri: ['Abdominaux inférieurs'], sec: ['Fléchisseurs de hanche', 'Hip flexors'], desc: 'Renforce les abdos inférieurs pour tirer le bassin en rétroversion.', inst: 'Allongé, genoux 90°. Ramène les genoux vers la poitrine en décollant le bassin du sol, contrôle la descente. 10–12 reps sans élan.', ci: ['Hernie hiatale (prudence)'], var: ['reverse crunch'] },
  { key: 'mob_bassin_wall_march_retroversion', name: 'Wall march — rétroversion', cat: 'Mobilité bassin', zone: 'lombaires', diff: 2, dur: 50, eq: 'Mur', pos: 'Dos au mur', pri: ['Abdominaux', 'Fessiers'], sec: ['Quadriceps', 'Fléchisseurs de hanche'], desc: 'Contrôle du bassin debout — transfert du dead bug à la verticalité.', inst: 'Dos au mur, lombaires plaquées. Marche sur place en gardant le contact lombaire-mur (rétroversion maintenue). 20–30 marches lentes.', ci: ['Douleur hanche en flexion'], var: ['wall march pelvic tilt'] },
  { key: 'mob_bassin_rdl_leger', name: 'Romanian deadlift léger', cat: 'Mobilité bassin', zone: 'ischios', diff: 2, dur: 45, eq: 'Haltères légers', pos: 'Debout', pri: ['Ischio-jambiers', 'Fessiers'], sec: ['Érecteurs du rachis', 'Mollets'], desc: 'Renforcement postérieur avec hinge de hanche — pattern anti-antéversion.', inst: 'Debout, charge légère. Pousse les fesses en arrière, barre près des cuisses, dos plat. Sens la tension ischios, remonte en serrant les fessiers. 8–10 reps.', ci: ['Lombalgie'], var: ['RDL léger'] },
  { key: 'mob_bassin_child_pose', name: "Child's pose", cat: 'Mobilité bassin', zone: 'dos', diff: 1, dur: 90, eq: 'Tapis', pos: 'Genoux — pose enfant', pri: ['Lombaires', 'Dos'], sec: ['Hanches', 'Épaules'], desc: 'Décompression lombaire et relâchement du bassin après travail de gainage.', inst: 'Genoux écartés, fesses sur talons, bras loin devant. Laisse le front descendre, respire dans le dos. 60–90 s.', ci: ['Genou douloureux en flexion profonde'], var: ['child pose', 'posture enfant'] },
  { key: 'mob_bassin_bear_crawl', name: 'Bear crawl', cat: 'Mobilité bassin', zone: 'tronc', diff: 2, dur: 45, eq: 'Tapis', pos: 'Quatre pattes genoux levés', pri: ['Core', 'Fessiers'], sec: ['Épaules', 'Quadriceps'], desc: 'Coordination tronc-bassin-épaules en charge dynamique légère.', inst: 'Genoux décollés de quelques cm, avance main et pied opposés. Dos plat, petits pas. 10–15 m aller, retour. Ne laisse pas les hanches osciller.', ci: ['Poignet douloureux'], var: ['bear crawl'] },

  // ── CHEVILLES (14 nouveaux) ──
  { key: 'mob_cheville_calf_stretch_tendue', name: 'Étirement mollet — jambe tendue', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 50, eq: 'Mur', pos: 'Fente jambe arrière tendue', pri: ['Gastrocnémiens'], sec: ['Soléaire', 'Fascia crural'], desc: 'Cible le gastrocnémien (genou tendu) — indispensable avant squat profond.', inst: 'Face au mur, jambe arrière tendue, talon au sol. Penche le buste vers le mur jusqu’à tension mollet haut. 30–45 s par jambe.', ci: ['Claquage mollet'], var: ['calf stretch straight leg'] },
  { key: 'mob_cheville_calf_stretch_flechie', name: 'Étirement mollet — jambe fléchie', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 50, eq: 'Mur', pos: 'Fente genou fléchi arrière', pri: ['Soléaire'], sec: ['Gastrocnémiens', 'Achille'], desc: 'Cible le soléaire — souvent le maillon limitant en squat profond.', inst: 'Même position mais genou arrière fléchi, talon au sol. Tension plus basse dans le mollet. 30–45 s.', ci: ['Tendinite achilléenne aiguë'], var: ['calf stretch bent knee'] },
  { key: 'mob_cheville_heel_walks', name: 'Heel walks', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 40, eq: 'Aucun', pos: 'Marche sur talons', pri: ['Tibial antérieur'], sec: ['Mollets', 'Cheville'], desc: 'Renforcement du tibial antérieur et mobilité en dorsiflexion dynamique.', inst: 'Marche 15–20 m sur les talons, orteils relevés, petits pas. Genoux légèrement fléchis. 2–3 passages.', ci: ['Douleur tibia antérieur aiguë'], var: ['heel walk'] },
  { key: 'mob_cheville_toe_walks', name: 'Toe walks', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 40, eq: 'Aucun', pos: 'Marche sur pointes', pri: ['Gastrocnémiens', 'Soléaire'], sec: ['Mollets', 'Pied'], desc: 'Renforcement plantariflexion et stabilité cheville en dynamique.', inst: 'Marche sur la pointe des pieds 15–20 m, chevilles stables. 2–3 passages. Descends lentement si tu veux ajouter excentrique.', ci: ['Entorse cheville'], var: ['toe walk'] },
  { key: 'mob_cheville_banded_ankle_mob', name: 'Banded ankle mobilization', cat: 'Mobilité chevilles', zone: 'mollets', diff: 2, dur: 45, eq: 'Élastique', pos: 'Fente', pri: ['Soléaire', 'Cheville'], sec: ['Gastrocnémiens'], desc: 'Traction articulaire + dorsiflexion pour gagner degrés de flexion cheville.', inst: 'Élastique autour de la cheville, ancrage devant. Fente, genou vers l’avant par-dessus l’élastique, talon au sol. 12–15 pulses par jambe.', ci: ['Fracture cheville'], var: ['banded ankle mobilization'] },
  { key: 'mob_cheville_single_leg_balance', name: 'Single leg balance', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 45, eq: 'Aucun', pos: 'Un pied', pri: ['Mollets', 'Tibial antérieur'], sec: ['Fessiers', 'Core'], desc: 'Stabilité proprioceptive — base de la prévention entorses.', inst: 'Un pied, genou souple, regard loin. 30–45 s par jambe. Progresse : yeux fermés, surface instable, légère flexion genou.', ci: ['Vertige'], var: ['single leg balance'] },
  { key: 'mob_cheville_foot_rockers', name: 'Foot rockers', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 40, eq: 'Aucun', pos: 'Debout', pri: ['Mollets', 'Tibial antérieur'], sec: ['Pied'], desc: 'Amplitude cheville en transfert avant-arrière — échauffement pied-cheville.', inst: 'Debout, bascule du talon aux orteils et retour, pieds parallèles. 15–20 reps fluides.', ci: ['Fasciite plantaire aiguë'], var: ['foot rockers'] },
  { key: 'mob_cheville_jump_rope_leger', name: 'Jump rope léger', cat: 'Mobilité chevilles', zone: 'mollets', diff: 2, dur: 60, eq: 'Corde à sauter', pos: 'Debout', pri: ['Mollets', 'Tibial antérieur'], sec: ['Pied', 'Genou'], desc: 'Réactivité cheville et endurance du pied — progressif après mobilité.', inst: 'Corde légère, sauts bas sur l’avant du pied, 30–60 s. Genoux souples. Arrête si douleur tendineuse achille.', ci: ['Tendinite achilléenne'], var: ['jump rope'] },
  { key: 'mob_cheville_ankle_cars', name: 'Ankle CARs', cat: 'Mobilité chevilles', zone: 'mollets', diff: 2, dur: 45, eq: 'Assis ou debout', pos: 'Jambe libre', pri: ['Mollets', 'Tibial antérieur'], sec: ['Cheville'], desc: 'Rotations articulaires contrôlées de la cheville sans charge.', inst: 'Assis, jambe libre : trace un cercle lent avec la pointe du pied (5 sens horaire, 5 anti-horaire). Isoler la cheville, pas la hanche.', ci: ['Cheville instable'], var: ['ankle CARs'] },
  { key: 'mob_cheville_slant_board_stretch', name: 'Slant board stretch', cat: 'Mobilité chevilles', zone: 'mollets', diff: 2, dur: 50, eq: 'Planche inclinée', pos: 'Debout incliné', pri: ['Gastrocnémiens', 'Soléaire'], sec: ['Fascia plantaire'], desc: 'Étirement mollet et dorsiflexion sur plan incliné — efficace et confortable.', inst: 'Pieds sur planche inclinée, genoux tendus puis variante genoux fléchis. Maintiens 30–45 s chaque. Dos droit.', ci: ['Vertige'], var: ['slant board'] },
  { key: 'mob_cheville_seated_dorsiflexion_raises', name: 'Seated dorsiflexion raises', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 40, eq: 'Chaise', pos: 'Assis', pri: ['Tibial antérieur'], sec: ['Mollets'], desc: 'Renforcement du tibial antérieur en amplitude — complément aux heel walks.', inst: 'Assis, pieds au sol. Lève les orteils vers le tibia sans lever les talons. 15–20 reps. Peut ajouter haltère sur les pieds pour résistance.', ci: ['Syndrome loge antérieur'], var: ['seated dorsiflexion'] },
  { key: 'mob_cheville_short_foot', name: 'Short foot exercise', cat: 'Mobilité chevilles', zone: 'mollets', diff: 2, dur: 45, eq: 'Aucun', pos: 'Assis ou debout', pri: ['Voûte plantaire', 'Intrinsèques du pied'], sec: ['Mollets', 'Tibial antérieur'], desc: 'Renforce la voûte plantaire — stabilité cheville et genou en chaîne.', inst: 'Pied à plat, « raccourcis » le pied en rapprochant l’avant du pied du talon sans flexer les orteils. Maintiens 5–8 s, 10 reps par pied.', ci: ['Fasciite plantaire aiguë'], var: ['short foot', 'pied court'] },
  { key: 'mob_cheville_barefoot_walking', name: 'Barefoot walking — marche pieds nus', cat: 'Mobilité chevilles', zone: 'mollets', diff: 1, dur: 120, eq: 'Surface sûre', pos: 'Marche', pri: ['Intrinsèques du pied', 'Mollets'], sec: ['Tibial antérieur', 'Cheville'], desc: 'Travail naturel du pied et des chevilles — à intégrer progressivement.', inst: 'Marche pieds nus 2–5 min sur surface propre et plane (herbe, tapis). Progression très graduelle pour éviter fasciite. Pas sur béton dur en début.', ci: ['Neuropathie pied', 'plaies pied'], var: ['barefoot walk'] },

  // ── CERVICALES (16 nouveaux) ──
  { key: 'mob_cervical_neck_flexion_stretch', name: 'Neck flexion stretch', cat: 'Mobilité cervicales', zone: 'cou', diff: 1, dur: 40, eq: 'Aucun', pos: 'Assis ou debout', pri: ['Splénius', 'Trapèzes'], sec: ['Sterno-cléido-mastoïdien'], desc: 'Étire l’arrière du cou — contre la posture tête en avant.', inst: 'Assis droit, laisse le menton descendre vers la poitrine sans tirer avec les mains. Maintiens 20–30 s. Respire. Ne force pas en bas du cou.', ci: ['Hernie cervicale'], var: ['neck flexion stretch'] },
  { key: 'mob_cervical_neck_extension_controlee', name: 'Neck extension contrôlée', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 35, eq: 'Aucun', pos: 'Assis', pri: ['Sterno-cléido-mastoïdien', 'Scalènes'], sec: ['Trapèzes supérieurs'], desc: 'Mobilité en extension sans écraser les facettes cervicales.', inst: 'Regard lentement vers le plafond sur une petite amplitude, mâchoire relâchée. 5–8 reps lentes. Arrête si vertige ou picotements bras.', ci: ['Sténose cervicale', 'vertige'], var: ['neck extension'] },
  { key: 'mob_cervical_rotation_lente', name: 'Rotation cervicale lente', cat: 'Mobilité cervicales', zone: 'cou', diff: 1, dur: 45, eq: 'Aucun', pos: 'Assis', pri: ['Sterno-cléido-mastoïdien', 'Splénius'], sec: ['Scalènes', 'Trapèzes'], desc: 'Mobilité rotationnelle essentielle pour la conduite et le travail bureau.', inst: 'Tourne la tête à gauche puis droite en fin d’amplitude confortable, 5 s par côté. 6–8 reps. Épaules immobiles.', ci: ['Vertebro-basilaire (prudence)'], var: ['neck rotation'] },
  { key: 'mob_cervical_inclinaison_laterale', name: 'Inclinaison latérale de tête', cat: 'Mobilité cervicales', zone: 'cou', diff: 1, dur: 45, eq: 'Aucun', pos: 'Assis', pri: ['Trapèzes supérieurs', 'Élévateur de la scapula'], sec: ['Scalènes', 'Sterno-cléido-mastoïdien'], desc: 'Étire le côté du cou — soulage tensions trapèzes supérieurs.', inst: 'Incline l’oreille vers l’épaule sans hausser l’épaule. Main opposée peut tirer très légèrement. 20–25 s par côté.', ci: ['Douleur bras irradiante'], var: ['lateral neck stretch'] },
  { key: 'mob_cervical_cervical_cars', name: 'Cervical CARs', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 50, eq: 'Aucun', pos: 'Assis', pri: ['Sterno-cléido-mastoïdien', 'Splénius'], sec: ['Trapèzes supérieurs', 'Scalènes'], desc: 'Rotations cervicales contrôlées sur toute l’amplitude disponible.', inst: 'Trace un cercle lent avec le nez : flexion, rotation, extension, rotation. 3 cercles par sens. Amplitude maximale SANS douleur.', ci: ['Vertige', 'hernie cervicale'], var: ['cervical CARs'] },
  { key: 'mob_cervical_upper_trap_stretch', name: 'Upper trap stretch', cat: 'Mobilité cervicales', zone: 'cou', diff: 1, dur: 45, eq: 'Aucun', pos: 'Assis', pri: ['Trapèzes supérieurs'], sec: ['Élévateur de la scapula', 'Splénius'], desc: 'Cible le trapèze supérieur souvent surchargé par le stress et les écrans.', inst: 'Assis, main derrière le dos pour abaisser l’épaule. Incline la tête à l’opposé. 25–30 s. Répète de l’autre côté.', ci: ['Douleur bras'], var: ['upper trap stretch'] },
  { key: 'mob_cervical_levator_scapulae_stretch', name: 'Levator scapulae stretch', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 45, eq: 'Aucun', pos: 'Assis', pri: ['Élévateur de la scapula'], sec: ['Trapèzes supérieurs', 'Scalènes'], desc: 'Étirement du levator — « coude dans l’oreille » post bureau.', inst: 'Tourne la tête 45° vers l’aisselle opposée, incline le menton vers cette aisselle. Main peut guider très légèrement. 25 s par côté.', ci: ['Douleur scapula'], var: ['levator scapulae stretch'] },
  { key: 'mob_cervical_thread_the_needle', name: 'Thread the needle', cat: 'Mobilité cervicales', zone: 'thoracique', diff: 1, dur: 50, eq: 'Tapis', pos: 'Quatre pattes', pri: ['Grand dorsal', 'Thoracique'], sec: ['Trapèzes', 'Cou'], desc: 'Rotation thoracique qui décharge les cervicales compensatoires.', inst: 'Quatre pattes, passe un bras sous l’autre, épaule au sol, hanche fixe. 8–10 respirations par côté. Rotation depuis le thorax.', ci: ['Épaule douloureuse'], var: ['thread the needle'] },
  { key: 'mob_cervical_scapular_retractions', name: 'Scapular retractions', cat: 'Mobilité cervicales', zone: 'épaules', diff: 1, dur: 40, eq: 'Élastique (optionnel)', pos: 'Debout ou assis', pri: ['Rhomboïdes', 'Trapèzes moyens'], sec: ['Deltoïdes postérieurs', 'Cou'], desc: 'Ramène les omoplates — soulage les cervicales en rééquilibrant les épaules.', inst: 'Bras tendus devant, tire les coudes en arrière en serrant les omoplates ensemble. Maintiens 2 s. 12–15 reps. Élastique autour des poignets pour résistance.', ci: ['Douleur aiguë épaule'], var: ['scapular retraction'] },
  { key: 'mob_cervical_iso_neck_flexion_avant', name: 'Isometric neck hold — avant', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 35, eq: 'Aucun', pos: 'Assis', pri: ['Fléchisseurs du cou', 'Sterno-cléido-mastoïdien'], sec: ['Trapèzes supérieurs'], desc: 'Renforcement isométrique sans mouvement — rééducation cervicale douce.', inst: 'Paume sur le front, pousse la tête contre la main sans bouger. Effort modéré 5–8 s. 5 reps. Cou long, pas de compression.', ci: ['Hernie cervicale aiguë'], var: ['isometric neck flexion'] },
  { key: 'mob_cervical_iso_neck_extension_arriere', name: 'Isometric neck hold — arrière', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 35, eq: 'Aucun', pos: 'Assis', pri: ['Extenseurs du cou', 'Splénius'], sec: ['Trapèzes supérieurs'], desc: 'Renforce l’arrière du cou pour tenir la tête alignée.', inst: 'Mains entrelacées derrière la tête, pousse en arrière contre les mains. 5–8 s × 5. Amplitude nulle, effort modéré.', ci: ['Sténose cervicale'], var: ['isometric neck extension'] },
  { key: 'mob_cervical_iso_neck_lateral', name: 'Isometric neck hold — latéral', cat: 'Mobilité cervicales', zone: 'cou', diff: 2, dur: 35, eq: 'Aucun', pos: 'Assis', pri: ['Scalènes', 'Sterno-cléido-mastoïdien'], sec: ['Trapèzes supérieurs'], desc: 'Stabilité latérale du cou — utile sports contact.', inst: 'Main sur le côté de la tête, résiste à l’inclinaison. 5–8 s par côté, 5 reps. Alterne gauche/droite.', ci: ['Douleur bras'], var: ['isometric neck lateral'] },
  { key: 'mob_cervical_shoulder_rolls', name: 'Shoulder rolls', cat: 'Mobilité cervicales', zone: 'épaules', diff: 1, dur: 40, eq: 'Aucun', pos: 'Debout', pri: ['Trapèzes supérieurs', 'Deltoïdes'], sec: ['Cou', 'Thoracique'], desc: 'Décharge les cervicales en mobilisant les épaules.', inst: 'Grands cercles d’épaules : 8 vers l’arrière, 8 vers l’avant. Respiration fluide. Évite de hausser les épaules vers les oreilles.', ci: ['Luxation épaule'], var: ['shoulder rolls'] },
  { key: 'mob_cervical_thoracic_foam_roller', name: 'Thoracic extension — foam roller', cat: 'Mobilité cervicales', zone: 'thoracique', diff: 2, dur: 55, eq: 'Rouleau mousse', pos: 'Rouleau transverse', pri: ['Thoracique', 'Grand dorsal'], sec: ['Pectoraux', 'Cou'], desc: 'Mobilise le haut du dos pour que le cou n’compense plus en extension.', inst: 'Rouleau sous les omoplates, mains derrière la tête. Extension thoracique sur le rouleau, lombaires et cou stables. 8–10 extensions lentes.', ci: ['Ostéoporose', 'hernie thoracique'], var: ['thoracic extension foam roller'] },
  { key: 'mob_cervical_prone_cobra', name: 'Prone cobra', cat: 'Mobilité cervicales', zone: 'dos', diff: 2, dur: 40, eq: 'Tapis', pos: 'Ventre au sol', pri: ['Érecteurs du rachis', 'Trapèzes inférieurs'], sec: ['Cou', 'Deltoïdes postérieurs'], desc: 'Renforce l’extension thoracique avec cou long — posture anti-bureau.', inst: 'Ventre au sol, lève légèrement poitrine et mains (optionnel). Regard au sol, cou long. 8–10 reps de 3 s. Pas de cambrure lombaire excessive.', ci: ['Lombalgie aiguë'], var: ['prone cobra'] },
  { key: 'mob_cervical_neck_glides', name: 'Neck glides', cat: 'Mobilité cervicales', zone: 'cou', diff: 1, dur: 40, eq: 'Aucun', pos: 'Assis', pri: ['Fléchisseurs du cou', 'Extenseurs du cou'], sec: ['Sterno-cléido-mastoïdien'], desc: 'Glissades avant-arrière du crâne sans incliner le menton — alignement cervical.', inst: 'Assis, cou long. Fais glisser la tête horizontalement en avant puis en arrière (comme un tiroir), menton parallèle au sol. 10 reps lentes.', ci: ['Vertige'], var: ['neck glides', 'cervical retractions'] }
];

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const lines = [
  '/**',
  ' * Catalogue mobilité (genoux, hanches, bassin, chevilles, cervicales).',
  ' * Fusionné dans stretchDatabase.js',
  ' */',
  'export const mobilityStretchCatalog = {'
];

for (const it of ITEMS) {
  const vars = it.var.map((v) => `"${esc(v)}"`).join(', ');
  const ci = it.ci.map((c) => `"${esc(c)}"`).join(', ');
  const pri = it.pri.map((m) => `"${esc(m)}"`).join(', ');
  const sec = it.sec.map((m) => `"${esc(m)}"`).join(', ');
  lines.push(`  ${it.key}: {
    name: "${esc(it.name)}",
    category: "${esc(it.cat)}",
    bodyZone: "${esc(it.zone)}",
    primaryMuscles: [${pri}],
    secondaryMuscles: [${sec}],
    equipment: "${esc(it.eq)}",
    defaultDuration: ${it.dur},
    position: "${esc(it.pos)}",
    difficulty: ${it.diff},
    description: "${esc(it.desc)}",
    instructions: "${esc(it.inst)}",
    contraindications: [${ci}],
    variations: [${vars}]
  },`);
}

lines.push('};');
lines.push('');
fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log('Wrote', ITEMS.length, 'entries to', OUT);
